package com.codeclan.example.breadboss.components;

import com.codeclan.example.breadboss.models.Ingredient;
import com.codeclan.example.breadboss.models.RawMaterial;
import com.codeclan.example.breadboss.models.Recipe;
import com.codeclan.example.breadboss.models.Supplier;
import com.codeclan.example.breadboss.repositories.IngredientRepository;
import com.codeclan.example.breadboss.repositories.RawMaterialRepository;
import com.codeclan.example.breadboss.repositories.RecipeRepository;
import com.codeclan.example.breadboss.repositories.SupplierRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.stereotype.Component;

@Component
public class DataLoader implements ApplicationRunner {

  @Autowired
  RawMaterialRepository rawMaterialRepository;

  @Autowired
  IngredientRepository ingredientRepository;

  @Autowired
  RecipeRepository recipeRepository;

  @Autowired
  SupplierRepository supplierRepository;

  public void run(ApplicationArguments args) {

    Supplier shiptonMill = new Supplier("Shipton Mill", "Bob", "Miller", "07999123456", "orders@shiptonmill.co.uk");
    Supplier mungoswells = new Supplier("Mungoswells", "Alison", "Miller", "07999123456", "orders@mungoswells.co.uk");
    Supplier morrisons = new Supplier("Morrisons", "Don", "Morrison", "07999123456", "orders@morrisons.co.uk");
    Supplier wholefoods = new Supplier("Wholefoods Online", "Max", "Davidson", "07999123456", "orders@wholefoods.co.uk");
    Supplier none = new Supplier("None", "N/A", "N/A", "N/A", "N/A");

    supplierRepository.save(shiptonMill);
    supplierRepository.save(mungoswells);
    supplierRepository.save(morrisons);
    supplierRepository.save(wholefoods);
    supplierRepository.save(none);
    RawMaterial ciabattaFlour = new RawMaterial("Flour - Ciabatta (T00)","Flour",shiptonMill,1000, (float) 1.30);
    RawMaterial rawMaterial2 = new RawMaterial("Flour - Einkorn","Flour",shiptonMill,1000, (float) 2.1);
    RawMaterial rawMaterial3 = new RawMaterial("Flour - Emmer","Flour",shiptonMill,1000, (float) 1.75);
    RawMaterial extraStrongFlour = new RawMaterial("Flour - Extra Strong","Flour",mungoswells,16000, (float) 13.55);
    RawMaterial rawMaterial5 = new RawMaterial("Flour - Granary","Flour",shiptonMill,1000, (float) 1.3);
    RawMaterial rawMaterial6 = new RawMaterial("Flour - Khorasan","Flour",shiptonMill,1000, (float) 1.75);
    RawMaterial darkRyeFlour = new RawMaterial("Flour - Rye Dark","Flour",mungoswells,16000, (float) 12.17);
    RawMaterial rawMaterial8 = new RawMaterial("Flour - Rye Light","Flour",shiptonMill,1000, (float) 1.3);
    RawMaterial rawMaterial9 = new RawMaterial("Flour - Spelt White","Flour",shiptonMill,1000, (float) 2.0);
    RawMaterial rawMaterial10 = new RawMaterial("Flour - Spelt Wholemeal","Flour",shiptonMill,1000, (float) 2.23);
    RawMaterial strongBreadFlour= new RawMaterial("Flour - Strong Bread","Flour",mungoswells,16000, (float) 16.09);
    RawMaterial T85 = new RawMaterial("Flour - T85","Flour",mungoswells,16000, (float) 15.40);
    RawMaterial wholewheatFlour = new RawMaterial("Flour - Wholewheat","Flour",mungoswells,16000, (float) 14.86);
    RawMaterial YQflour = new RawMaterial("Flour - YQ","Flour",morrisons,3000, (float) 4.99);
    RawMaterial ale = new RawMaterial("Ale","Liquid",morrisons,500, (float) 1.25);
    RawMaterial water = new RawMaterial("Water","Liquid",none,0, (float) 0.0);
    RawMaterial rawMaterial19 = new RawMaterial("5 Grain Blend","Other",shiptonMill,1000, (float) 1.3);
    RawMaterial beetroot = new RawMaterial("Beetroot - Roasted","Other",morrisons,200, (float) 1.7);
    RawMaterial misoPaste = new RawMaterial("Miso","Other",wholefoods,300, (float) 3.0);
    RawMaterial oliveOil = new RawMaterial("Olive Oil","Other",morrisons,750, (float) 2.39);
    RawMaterial rawMaterial23 = new RawMaterial("Olives - Green","Other",morrisons,340, (float) 0.59);
    RawMaterial rawMaterial24 = new RawMaterial("Olives - Kalamata","Other",morrisons,335, (float) 1.9);
    RawMaterial pearlBarley = new RawMaterial("Pearl Barley","Other",morrisons,500, (float) 0.53);
    RawMaterial rawMaterial26 = new RawMaterial("Rosemary","Other",morrisons,31, (float) 0.72);
    RawMaterial rawMaterial27 = new RawMaterial("Seeds - Black Sesame","Other",wholefoods,100, (float) 1.5);
    RawMaterial flaxSeeds = new RawMaterial("Seeds - Flax","Other",wholefoods,1000, (float) 3.89);
    RawMaterial chiaSeeds = new RawMaterial("Seeds - Chia","Other",wholefoods,1000, (float) 5.89);
    RawMaterial cuminSeeds = new RawMaterial("Seeds - Cumin","Other",morrisons,37, (float) 0.8);
    RawMaterial pumpkinSeeds = new RawMaterial("Seeds - Pumpkin","Other",wholefoods,1000, (float) 6.47);
    RawMaterial sunflowerSeeds = new RawMaterial("Seeds - Sunflower","Other",wholefoods,1000, (float) 3.67);
    RawMaterial caraway = new RawMaterial("Seeds - Caraway","Other",wholefoods,100, (float) 3.67);
    RawMaterial rawMaterial33 = new RawMaterial("Seeds - White Sesame","Other",wholefoods,1000, (float) 4.91);
    RawMaterial sesameOil = new RawMaterial("Sesame Oil","Other",morrisons,250, (float) 1.8);
    RawMaterial rawMaterial35 = new RawMaterial("Sweet Potato - Dried","Other",morrisons,500, (float) 1.0);
    RawMaterial rawMaterial36 = new RawMaterial("Sweet Potato - Fresh","Other",morrisons,1000, (float) 1.0);
    RawMaterial walnuts = new RawMaterial("Walnuts","Other",wholefoods,1000, (float) 8.99);
    RawMaterial salt = new RawMaterial("Sea Salt","Salt",morrisons,350, (float) 0.8);
    RawMaterial ryeStarter = new RawMaterial("Starter - Rye","Starter",none,0, (float) 0.0);
    RawMaterial wheatStarter = new RawMaterial("Starter - Wheat","Starter",none,0, (float) 0.0);
    RawMaterial sugar = new RawMaterial("Sugar - granulated","Other",morrisons,1000, (float) 0.8);
    RawMaterial yeast = new RawMaterial("Yeast - Fresh","Yeast",morrisons,100, (float) 0.5);
    rawMaterialRepository.save(ciabattaFlour);
    rawMaterialRepository.save(rawMaterial2);
    rawMaterialRepository.save(rawMaterial3);
    rawMaterialRepository.save(extraStrongFlour);
    rawMaterialRepository.save(rawMaterial5);
    rawMaterialRepository.save(rawMaterial5);
    rawMaterialRepository.save(rawMaterial6);
    rawMaterialRepository.save(darkRyeFlour);
    rawMaterialRepository.save(rawMaterial8);
    rawMaterialRepository.save(rawMaterial9);
    rawMaterialRepository.save(rawMaterial10);
    rawMaterialRepository.save(strongBreadFlour);
    rawMaterialRepository.save(T85);
    rawMaterialRepository.save(wholewheatFlour);
    rawMaterialRepository.save(YQflour);
    rawMaterialRepository.save(ale);
    rawMaterialRepository.save(water);
    rawMaterialRepository.save(rawMaterial19);
    rawMaterialRepository.save(beetroot);
    rawMaterialRepository.save(misoPaste);
    rawMaterialRepository.save(oliveOil);
    rawMaterialRepository.save(rawMaterial23);
    rawMaterialRepository.save(rawMaterial24);
    rawMaterialRepository.save(pearlBarley);
    rawMaterialRepository.save(rawMaterial26);
    rawMaterialRepository.save(salt);
    rawMaterialRepository.save(sugar);
    rawMaterialRepository.save(rawMaterial27);
    rawMaterialRepository.save(caraway);
    rawMaterialRepository.save(chiaSeeds);
    rawMaterialRepository.save(cuminSeeds);
    rawMaterialRepository.save(flaxSeeds);
    rawMaterialRepository.save(pumpkinSeeds);
    rawMaterialRepository.save(sunflowerSeeds);
    rawMaterialRepository.save(rawMaterial33);
    rawMaterialRepository.save(sesameOil);
    rawMaterialRepository.save(rawMaterial35);
    rawMaterialRepository.save(rawMaterial36);

    rawMaterialRepository.save(ryeStarter);
    rawMaterialRepository.save(wheatStarter);
    rawMaterialRepository.save(walnuts);
    rawMaterialRepository.save(yeast);


    Recipe recipe1 = new Recipe("50:50 Wholewheat Sourdough","Sourdough");
    recipe1.setImageUrl("5050wholewheat.jpg");
    recipeRepository.save(recipe1);
    Ingredient ingredient1 = new Ingredient(recipe1, wholewheatFlour, "Levain", 1000 );
    Ingredient ingredient2 = new Ingredient(recipe1, water, "Levain", 600 );
    Ingredient ingredient3 = new Ingredient(recipe1, ryeStarter, "Levain", 100 );
    Ingredient ingredient4 = new Ingredient(recipe1, strongBreadFlour, "Dough", 3500 );
    Ingredient ingredient5 = new Ingredient(recipe1, wholewheatFlour, "Dough", 2500 );
    Ingredient ingredient6 = new Ingredient(recipe1, salt, "Dough", 140 );
    Ingredient ingredient7 = new Ingredient(recipe1, water, "Dough", 4700 );
    ingredientRepository.save(ingredient1);
    ingredientRepository.save(ingredient2);
    ingredientRepository.save(ingredient3);
    ingredientRepository.save(ingredient4);
    ingredientRepository.save(ingredient5);
    ingredientRepository.save(ingredient6);
    ingredientRepository.save(ingredient7);

  Recipe focaccia = new Recipe("Focaccia", "Preferment");
  focaccia.setImageUrl("focaccia.jpg");
  recipeRepository.save(focaccia);
  Ingredient ingredient8 = new Ingredient(focaccia, ciabattaFlour, "Levain", 400);
  Ingredient ingredient9 = new Ingredient(focaccia, water, "Levain", 400);
  Ingredient ingredient10 = new Ingredient(focaccia, yeast, "Levain", 1);
  Ingredient ingredient11 = new Ingredient(focaccia, ciabattaFlour, "Dough", 600);
  Ingredient ingredient12 = new Ingredient(focaccia, salt, "Dough", 20);
  Ingredient ingredient13 = new Ingredient(focaccia, water, "Dough", 320);
  Ingredient ingredient14 = new Ingredient(focaccia, oliveOil, "Dough", 60);
  Ingredient ingredient15 = new Ingredient(focaccia, yeast, "Dough", 8);
    ingredientRepository.save(ingredient8);
    ingredientRepository.save(ingredient9);
    ingredientRepository.save(ingredient10);
    ingredientRepository.save(ingredient11);
    ingredientRepository.save(ingredient12);
    ingredientRepository.save(ingredient13);
    ingredientRepository.save(ingredient14);
    ingredientRepository.save(ingredient15);
    
    Recipe recipe3 = new Recipe("Chia & Flaxseed Sourdough", "Sourdough");
    recipe3.setImageUrl("chia.jpg");
    recipeRepository.save(recipe3);
    Ingredient ingredient16 = new Ingredient(recipe3, strongBreadFlour, "Levain", 150);
    Ingredient ingredient17 = new Ingredient(recipe3, water, "Levain", 120);
    Ingredient ingredient18 = new Ingredient(recipe3, wheatStarter, "Levain", 30);
    Ingredient ingredient19 = new Ingredient(recipe3, T85, "Dough", 100);
    Ingredient ingredient20 = new Ingredient(recipe3, strongBreadFlour, "Dough", 500);
    Ingredient ingredient21 = new Ingredient(recipe3, wholewheatFlour, "Dough", 250);
    Ingredient ingredient22 = new Ingredient(recipe3, salt, "Dough", 18);
    Ingredient ingredient23 = new Ingredient(recipe3, water, "Dough", 730);
    Ingredient ingredient24 = new Ingredient(recipe3, chiaSeeds, "Dough", 70);
    Ingredient ingredient25 = new Ingredient(recipe3, flaxSeeds, "Dough", 70);

    ingredientRepository.save(ingredient16);
    ingredientRepository.save(ingredient17);
    ingredientRepository.save(ingredient18);
    ingredientRepository.save(ingredient19);
    ingredientRepository.save(ingredient20);
    ingredientRepository.save(ingredient21);
    ingredientRepository.save(ingredient22);
    ingredientRepository.save(ingredient23);
    ingredientRepository.save(ingredient24);
    ingredientRepository.save(ingredient25);

    Recipe recipe4 = new Recipe("Barley Grain and Ale Sourdough", "Sourdough");
    recipe4.setImageUrl("BGA.jpg");
    recipeRepository.save(recipe4);
    Ingredient ingredient26 = new Ingredient(recipe4, strongBreadFlour, "Levain", 600);
    Ingredient ingredient27 = new Ingredient(recipe4, water, "Levain", 480);
    Ingredient ingredient28 = new Ingredient(recipe4, wheatStarter, "Levain", 120);
    Ingredient ingredient29 = new Ingredient(recipe4, strongBreadFlour, "Dough", 4000);
    Ingredient ingredient30 = new Ingredient(recipe4, wholewheatFlour, "Dough", 400);
    Ingredient ingredient31 = new Ingredient(recipe4, salt, "Dough", 100);
    Ingredient ingredient32 = new Ingredient(recipe4, water, "Dough", 2400);
    Ingredient ingredient33 = new Ingredient(recipe4, ale, "Dough", 1000);
    Ingredient ingredient34 = new Ingredient(recipe4, flaxSeeds, "Dough", 300);
    Ingredient ingredient35 = new Ingredient(recipe4, sunflowerSeeds, "Dough", 300);
    Ingredient ingredient36 = new Ingredient(recipe4, pearlBarley, "Dough", 350);
    ingredientRepository.save(ingredient26);
    ingredientRepository.save(ingredient27);
    ingredientRepository.save(ingredient28);
    ingredientRepository.save(ingredient29);
    ingredientRepository.save(ingredient30);
    ingredientRepository.save(ingredient31);
    ingredientRepository.save(ingredient32);
    ingredientRepository.save(ingredient33);
    ingredientRepository.save(ingredient34);
    ingredientRepository.save(ingredient35);
    ingredientRepository.save(ingredient36);

    Recipe ciabatta = new Recipe("Ciabatta", "Preferment");
    ciabatta.setImageUrl("ciabatta.jpg");
    recipeRepository.save(ciabatta);
    Ingredient ingredient37 = new Ingredient(ciabatta, ciabattaFlour, "Levain", 3600);
    Ingredient ingredient38 = new Ingredient(ciabatta, water, "Levain", 2160);
    Ingredient ingredient39 = new Ingredient(ciabatta, yeast, "Levain", 5);
    Ingredient ingredient40 = new Ingredient(ciabatta, ciabattaFlour, "Dough", 4200);
    Ingredient ingredient41 = new Ingredient(ciabatta, salt, "Dough", 156);
    Ingredient ingredient42 = new Ingredient(ciabatta, water, "Dough", 4080);
    Ingredient ingredient43 = new Ingredient(ciabatta, oliveOil, "Dough", 78);
    Ingredient ingredient44 = new Ingredient(ciabatta, yeast, "Dough", 30);
    ingredientRepository.save(ingredient37);
    ingredientRepository.save(ingredient38);
    ingredientRepository.save(ingredient39);
    ingredientRepository.save(ingredient40);
    ingredientRepository.save(ingredient41);
    ingredientRepository.save(ingredient42);
    ingredientRepository.save(ingredient43);
    ingredientRepository.save(ingredient44);

    Recipe morningRolls = new Recipe("Sourdough Scotch Morning Rolls", "Sourdough");
    morningRolls.setImageUrl("morningrolls.jpg");
    recipeRepository.save(morningRolls);
    Ingredient ingredient45 = new Ingredient(morningRolls, strongBreadFlour, "Levain", 3500);
    Ingredient ingredient46 = new Ingredient(morningRolls, water, "Levain", 2100);
    Ingredient ingredient47 = new Ingredient(morningRolls, wheatStarter, "Levain", 350);
    Ingredient ingredient48 = new Ingredient(morningRolls, strongBreadFlour, "Dough", 24500);
    Ingredient ingredient49 = new Ingredient(morningRolls, wholewheatFlour, "Dough", 3500);
    Ingredient ingredient50 = new Ingredient(morningRolls, extraStrongFlour, "Dough", 4000);
    Ingredient ingredient51 = new Ingredient(morningRolls, salt, "Dough", 500);
    Ingredient ingredient52 = new Ingredient(morningRolls, water, "Dough", 19200);
    Ingredient ingredient53 = new Ingredient(morningRolls, yeast, "Dough", 1300);
    Ingredient ingredient54 = new Ingredient(morningRolls, oliveOil, "Dough", 700);
    Ingredient ingredient55 = new Ingredient(morningRolls, sugar, "Dough", 460);
    ingredientRepository.save(ingredient45);
    ingredientRepository.save(ingredient46);
    ingredientRepository.save(ingredient47);
    ingredientRepository.save(ingredient48);
    ingredientRepository.save(ingredient49);
    ingredientRepository.save(ingredient50);
    ingredientRepository.save(ingredient51);
    ingredientRepository.save(ingredient52);
    ingredientRepository.save(ingredient53);
    ingredientRepository.save(ingredient54);
    ingredientRepository.save(ingredient55);

    Recipe tourte = new Recipe("Tourte au Seigle", "Sourdough");
    tourte.setImageUrl("tourte.jpg");
    recipeRepository.save(tourte);
    Ingredient ingredient56 = new Ingredient(tourte, darkRyeFlour, "Levain", 2400);
    Ingredient ingredient57 = new Ingredient(tourte, water, "Levain", 2400);
    Ingredient ingredient58 = new Ingredient(tourte, ryeStarter, "Levain", 600);
    Ingredient ingredient59 = new Ingredient(tourte, darkRyeFlour, "Dough", 2400);
    Ingredient ingredient60 = new Ingredient(tourte, wholewheatFlour, "Dough", 1800);
    Ingredient ingredient61 = new Ingredient(tourte, salt, "Dough", 120);
    Ingredient ingredient62 = new Ingredient(tourte, water, "Dough", 3120);
    ingredientRepository.save(ingredient56);
    ingredientRepository.save(ingredient57);
    ingredientRepository.save(ingredient58);
    ingredientRepository.save(ingredient59);
    ingredientRepository.save(ingredient60);
    ingredientRepository.save(ingredient61);
    ingredientRepository.save(ingredient62);

    Recipe beetrootSD = new Recipe("Beetroot, Pumpkin Seed & Cumin Sourdough", "Sourdough");
    beetrootSD.setImageUrl("beetroot.jpg");
    recipeRepository.save(beetrootSD);
    Ingredient ingredient63 = new Ingredient(beetrootSD, strongBreadFlour, "Levain", 625);
    Ingredient ingredient64 = new Ingredient(beetrootSD, water, "Levain", 500);
    Ingredient ingredient65 = new Ingredient(beetrootSD, wheatStarter, "Levain", 125);
    Ingredient ingredient66 = new Ingredient(beetrootSD, strongBreadFlour, "Dough", 3675);
    Ingredient ingredient67 = new Ingredient(beetrootSD, salt, "Dough", 80);
    Ingredient ingredient68 = new Ingredient(beetrootSD, water, "Dough", 2600);
    Ingredient ingredient69 = new Ingredient(beetrootSD, beetroot, "Dough", 800);
    Ingredient ingredient70 = new Ingredient(beetrootSD, pumpkinSeeds, "Dough", 800);
    Ingredient ingredient71 = new Ingredient(beetrootSD, cuminSeeds, "Dough", 22);
    ingredientRepository.save(ingredient63);
    ingredientRepository.save(ingredient64);
    ingredientRepository.save(ingredient65);
    ingredientRepository.save(ingredient66);
    ingredientRepository.save(ingredient67);
    ingredientRepository.save(ingredient68);
    ingredientRepository.save(ingredient69);
    ingredientRepository.save(ingredient70);
    ingredientRepository.save(ingredient71);

    Recipe YQ = new Recipe("YQ Sourdough", "Sourdough");
    YQ.setImageUrl("YQ.jpg");
    recipeRepository.save(YQ);
    Ingredient ingredient72 = new Ingredient(YQ, YQflour, "Levain", 2000);
    Ingredient ingredient73 = new Ingredient(YQ, water, "Levain", 1200);
    Ingredient ingredient74 = new Ingredient(YQ, wheatStarter, "Levain", 400);
    Ingredient ingredient75 = new Ingredient(YQ, YQflour, "Dough", 5000);
    Ingredient ingredient76 = new Ingredient(YQ, extraStrongFlour, "Dough", 3000);
    Ingredient ingredient77 = new Ingredient(YQ, salt, "Dough", 180);
    Ingredient ingredient78 = new Ingredient(YQ, water, "Dough", 6000);
    ingredientRepository.save(ingredient72);
    ingredientRepository.save(ingredient73);
    ingredientRepository.save(ingredient74);
    ingredientRepository.save(ingredient75);
    ingredientRepository.save(ingredient76);
    ingredientRepository.save(ingredient77);
    ingredientRepository.save(ingredient78);

    Recipe NYDR = new Recipe("New York Deli Rye Sourdough", "Sourdough");
    NYDR.setImageUrl("NYDR.jpg");
    recipeRepository.save(NYDR);
    Ingredient ingredient79 = new Ingredient(NYDR, darkRyeFlour, "Levain", 200);
    Ingredient ingredient80 = new Ingredient(NYDR, water, "Levain", 120);
    Ingredient ingredient81 = new Ingredient(NYDR, ryeStarter, "Levain", 50);
    Ingredient ingredient82 = new Ingredient(NYDR, strongBreadFlour, "Dough", 750);
    Ingredient ingredient83 = new Ingredient(NYDR, wholewheatFlour, "Dough", 50);
    Ingredient ingredient84 = new Ingredient(NYDR, salt, "Dough", 22);
    Ingredient ingredient85 = new Ingredient(NYDR, water, "Dough", 540);
    Ingredient ingredient86 = new Ingredient(NYDR, caraway, "Dough", 10);
    ingredientRepository.save(ingredient79);
    ingredientRepository.save(ingredient80);
    ingredientRepository.save(ingredient81);
    ingredientRepository.save(ingredient82);
    ingredientRepository.save(ingredient83);
    ingredientRepository.save(ingredient84);
    ingredientRepository.save(ingredient85);
    ingredientRepository.save(ingredient86);

    Recipe miso = new Recipe("Miso & Sesame Sourdough", "Sourdough");
    miso.setImageUrl("miso.jpg");
    recipeRepository.save(miso);
    Ingredient ingredient87 = new Ingredient(miso, strongBreadFlour, "Levain", 100);
    Ingredient ingredient88 = new Ingredient(miso, water, "Levain", 80);
    Ingredient ingredient89 = new Ingredient(miso, wheatStarter, "Levain", 20);
    Ingredient ingredient90 = new Ingredient(miso, strongBreadFlour, "Dough", 700);
    Ingredient ingredient91 = new Ingredient(miso, wholewheatFlour, "Dough", 300);
    Ingredient ingredient92 = new Ingredient(miso, T85, "Dough", 100);
    Ingredient ingredient93 = new Ingredient(miso, salt, "Dough", 17);
    Ingredient ingredient94 = new Ingredient(miso, water, "Dough", 780);
    Ingredient ingredient95 = new Ingredient(miso, misoPaste, "Dough", 50);
    Ingredient ingredient96 = new Ingredient(miso, sesameOil, "Dough", 15);
    ingredientRepository.save(ingredient87);
    ingredientRepository.save(ingredient88);
    ingredientRepository.save(ingredient89);
    ingredientRepository.save(ingredient90);
    ingredientRepository.save(ingredient91);
    ingredientRepository.save(ingredient92);
    ingredientRepository.save(ingredient93);
    ingredientRepository.save(ingredient94);
    ingredientRepository.save(ingredient95);
    ingredientRepository.save(ingredient96);

    Recipe ww = new Recipe("Wholewheat Sourdough", "Sourdough");
    ww.setImageUrl("wholewheat.jpg");
    recipeRepository.save(ww);
    Ingredient ingredient97 = new Ingredient(ww, wholewheatFlour, "Levain", 2000);
    Ingredient ingredient98 = new Ingredient(ww, water, "Levain", 1200);
    Ingredient ingredient99 = new Ingredient(ww, wheatStarter, "Levain", 400);
    Ingredient ingredient100 = new Ingredient(ww, wholewheatFlour, "Dough", 5500);
    Ingredient ingredient101 = new Ingredient(ww, extraStrongFlour, "Dough", 2500);
    Ingredient ingredient102 = new Ingredient(ww, salt, "Dough", 180);
    Ingredient ingredient103 = new Ingredient(ww, water, "Dough", 6800);
    ingredientRepository.save(ingredient97);
    ingredientRepository.save(ingredient98);
    ingredientRepository.save(ingredient99);
    ingredientRepository.save(ingredient100);
    ingredientRepository.save(ingredient101);
    ingredientRepository.save(ingredient102);
    ingredientRepository.save(ingredient103);

    Recipe walnutSD = new Recipe("Walnut Sourdough", "Sourdough");
    walnutSD.setImageUrl("walnut.jpg");
    recipeRepository.save(walnutSD);
    Ingredient ingredient104 = new Ingredient(walnutSD, darkRyeFlour, "Levain", 560);
    Ingredient ingredient105 = new Ingredient(walnutSD, T85, "Levain", 560);
    Ingredient ingredient106 = new Ingredient(walnutSD, water, "Levain", 1050);
    Ingredient ingredient107 = new Ingredient(walnutSD, wheatStarter, "Levain", 245);
    Ingredient ingredient108 = new Ingredient(walnutSD, strongBreadFlour, "Dough", 5880);
    Ingredient ingredient109 = new Ingredient(walnutSD, salt, "Dough", 140);
    Ingredient ingredient110 = new Ingredient(walnutSD, water, "Dough", 4200);
    Ingredient ingredient111 = new Ingredient(walnutSD, walnuts, "Dough", 1680);
    ingredientRepository.save(ingredient104);
    ingredientRepository.save(ingredient105);
    ingredientRepository.save(ingredient106);
    ingredientRepository.save(ingredient107);
    ingredientRepository.save(ingredient108);
    ingredientRepository.save(ingredient109);
    ingredientRepository.save(ingredient110);
    ingredientRepository.save(ingredient111);




  }
}
